# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Plume"
license = "MIT"
description = "Plume is a theme for Hugo! static websites generator, based on Chota CSS framework and optimised to be eco-friendly"
homepage = ""
tags = ["blog", "company", "portfolio", "projects", "minimalist", "responsive", "milligram", "eco-friendly", "light", "dark", "mobile", "concatenation", "minification"]
features = []
min_version = "0.41.0"

copyright=""
[author]
  name = "Jonathan Courbon"
  homepage = "https://github.com/JonCourbon"
